apiVersion: v1
kind: Secret
metadata:
 name: rotc-secret
 namespace: crud-app
type: Opaque
data:
 db-password: QXAwMHJQYSQkdzByZCE=

---

apiVersion: v1
kind: Pod
metadata:
 namespace: crud-app
 name: post-gres
 labels:
  app: post-gres
spec:
 containers:
  - name: postgres
    image: postgres:16
    ports:
     - containerPort: 5432
    env:
     - name: POSTGRES_PASSWORD
       valueFrom:
        secretKeyRef:
         name: rotc-secret
         key: db-password
     - name: POSTGRES_DB
       value: postgres
     - name: POSTGRES_USER
       value: postgres
    volumeMounts:  
     - name: postgres-storage
       mountPath: /var/lib/postgresql/data
 volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: pvc-data
 restartPolicy: Always 

---

apiVersion: v1
kind: Service
metadata:
  namespace: crud-app
  name: postgres-service
  labels:
    app: postgres-service
spec:
  type: ClusterIP
  selector:
    app: post-gres
  ports: 
   - port: 5432
     targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crud-app
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
       app: backend 
  template: 
    metadata:
      name: backend 
      labels:
        app: backend 
    spec:
      restartPolicy: Always
      containers: 
       - name: backend
         image: final_assignment-backend
         imagePullPolicy: Never
         ports:
           - containerPort: 8000
         env:
          - name: db_address
            value: postgres-service
          - name: db_username
            value: postgres
          - name: db_name 
            value: postgres
          - name: db_password 
            valueFrom:
             secretKeyRef:
               name: rotc-secret
               key: db-password
 
---

 apiVersion: v1
 kind: Service   
 metadata:
  name: backend-service
  namespace: crud-app
  labels:
    app: backend-service
 spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000

---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: crud-app
  name: pv-data
  labels:
    app: pv-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app/backend/data 
  storageClassName: manual

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: crud-app
  name: pvc-data
  labels:
    app: pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
