apiVersion: v1
kind: Pod
metadata:
 namespace: crud-app
 name: post-gres
 labels:
  app: post-gres
spec:
 containers:
  - name: postgres
    image: postgres:16
    ports:
     - containerPort: 5432
    env:
     - name: POSTGRES_PASSWORD
       valueFrom:
        secretKeyRef:
         name: rotc-secret
         key: db-password
     - name: POSTGRES_DB
       value: postgres
     - name: POSTGRES_USER
       value: postgres
    volumeMounts:  
     - name: postgres-storage
       mountPath: /var/lib/postgresql/data
 volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: pvc-data
 restartPolicy: Always 

