apiVersion: v1
kind: Service
metadata:
  namespace: crud-app
  name: postgres-service
  labels:
    app: postgres-service
spec:
  type: ClusterIP
  selector:
    app: post-gres
  ports: 
   - port: 5432
     targetPort: 5432
