apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: crud-app
  name: pv-data
  labels:
    app: pv-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app/backend/data 
  storageClassName: manual
