apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: crud-app
  name: pvc-data
  labels:
    app: pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
